/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author martin_cervantes
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple MySQL Connection");

        jButton1.setText("Conexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nuevo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3))
                    .addComponent(jButton1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            String conexionURL = "jdbc:mysql://localhost:3306/escuela";
            String user =  "Admin";
            String password = "123456";
            
            Connection conexion = DriverManager.getConnection(conexionURL, user, password);
            
            JOptionPane.showMessageDialog(null, "Conexion exitosa","MySQL",JOptionPane.INFORMATION_MESSAGE);
            
            conexion.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MySQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
        {
            String conexionURL = "jdbc:mysql://localhost:3306/escuela";
            String user =  "Admin";
            String password = "123456";
            
            Connection conexion = DriverManager.getConnection(conexionURL, user, password);
            
            String comando = "INSERT INTO alumnos(nombre, apaterno, amaterno) VALUES(?, ?, ?)";
            
            PreparedStatement preparedStmt = conexion.prepareStatement(comando);
            preparedStmt.setString(1, "Martin");
            preparedStmt.setString(2, "Cervantes");
            preparedStmt.setString(3, "Palomo");

            preparedStmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro Guardado","MySQL",JOptionPane.INFORMATION_MESSAGE);
            
            conexion.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MySQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String mensaje = "";
        
        try
        {
            String conexionURL = "jdbc:mysql://localhost:3306/escuela";
            String user =  "Admin";
            String password = "123456";
            
            Connection conexion = DriverManager.getConnection(conexionURL, user, password);
            
            String comando = "SELECT * FROM alumnos";
            
            Statement statement = conexion.createStatement();
            
            ResultSet resultSet = statement.executeQuery(comando);
            
            while (resultSet.next())
            {
                int no_control = resultSet.getInt("no_control");
                String nombre = resultSet.getString("nombre");
                String apaterno = resultSet.getString("apaterno");
                String amaterno = resultSet.getString("amaterno");

                mensaje += no_control + "\t" + nombre + "\t" + apaterno + "\t" + amaterno + "\n";
            }
            
            JOptionPane.showMessageDialog(null, mensaje,"MySQL",JOptionPane.INFORMATION_MESSAGE);
            
            conexion.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MySQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            String conexionURL = "jdbc:mysql://localhost:3306/escuela";
            String user =  "Admin";
            String password = "123456";
            
            Connection conexion = DriverManager.getConnection(conexionURL, user, password);
            
            String comando = "DELETE FROM alumnos WHERE nombre = ?";
            
            PreparedStatement preparedStmt = conexion.prepareStatement(comando);
            preparedStmt.setString(1, "Martin");

            preparedStmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro Borrado","MySQL",JOptionPane.INFORMATION_MESSAGE);
            
            conexion.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MySQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
            String conexionURL = "jdbc:mysql://localhost:3306/escuela";
            String user =  "Admin";
            String password = "123456";
            
            Connection conexion = DriverManager.getConnection(conexionURL, user, password);
            
            String comando = "UPDATE alumnos SET no_control = 91645 WHERE nombre = ?";
            
            PreparedStatement preparedStmt = conexion.prepareStatement(comando);
            preparedStmt.setString(1, "Martin");

            preparedStmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro Actualizado","MySQL",JOptionPane.INFORMATION_MESSAGE);
            
            conexion.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MySQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}

