CREATE TABLE cuestionario (carrera INT, cuatrimestre INT, grupo VARCHAR(10), edad INT, sexo INT,
                    computadora INT, laptop INT, tablet INT, smart INT, noTengo INT,
                    Facebook1 INT, YouTube1 INT, Instagram1 INT, LinkedIn1 INT, Google1 INT, Twitter1 INT, WhatsApp1 INT, Messenger1 INT,
                    SnapChat1 INT, Classmates1 INT, Academia1 INT, StudiVZ1 INT, EducaNetwork1 INT, Edmodo1 INT, Schoology1 INT, Brainly1 INT,
                    Eduredes1 INT, Docsity1 INT, OtraEducacion1 INT, RedAlumnos1 INT, Educared1 INT, Eduteka1 INT, Skype1 INT, Badoo1 INT, total1 INT,
                    Facebook2 INT, YouTube2 INT, Instagram2 INT, LinkedIn2 INT, Google2 INT, Twitter2 INT, WhatsApp2 INT, Messenger2 INT,
                    SnapChat2 INT, Classmates2 INT, Academia2 INT, StudiVZ2 INT, EducaNetwork2 INT, Edmodo2 INT, Schoology2 INT, Brainly2 INT,
                    Eduredes2 INT, Docsity2 INT, OtraEducacion2 INT, RedAlumnos2 INT, Educared2 INT, Eduteka2 INT, Skype2 INT, Badoo2 INT, total2 INT,
                    Facebook3 INT, YouTube3 INT, Instagram3 INT, LinkedIn3 INT, Google3 INT, Twitter3 INT, WhatsApp3 INT, Messenger3 INT,
                    SnapChat3 INT, Classmates3 INT, Academia3 INT, StudiVZ3 INT, EducaNetwork3 INT, Edmodo3 INT, Schoology3 INT, Brainly3 INT,
                    Eduredes3 INT, Docsity3 INT, OtraEducacion3 INT, RedAlumnos3 INT, Educared3 INT, Eduteka3 INT, Skype3 INT, Badoo3 INT, total3 INT,
                    Facebook4 INT, YouTube4 INT, Instagram4 INT, LinkedIn4 INT, Google4 INT, Twitter4 INT, WhatsApp4 INT, Messenger4 INT,
                    SnapChat4 INT, Classmates4 INT, Academia4 INT, StudiVZ4 INT, EducaNetwork4 INT, Edmodo4 INT, Schoology4 INT, Brainly4 INT,
                    Eduredes4 INT, Docsity4 INT, OtraEducacion4 INT, RedAlumnos4 INT, Educared4 INT, Eduteka4 INT, Skype4 INT, Badoo4 INT, total4 INT,
                    Facebook5 INT, YouTube5 INT, Instagram5 INT, LinkedIn5 INT, Google5 INT, Twitter5 INT, WhatsApp5 INT, Messenger5 INT,
                    SnapChat5 INT, Classmates5 INT, Academia5 INT, StudiVZ5 INT, EducaNetwork5 INT, Edmodo5 INT, Schoology5 INT, Brainly5 INT,
                    Eduredes5 INT, Docsity5 INT, OtraEducacion5 INT, RedAlumnos5 INT, Educared5 INT, Eduteka5 INT, Skype5 INT, Badoo5 INT, total5 INT,
                    Facebook6 INT, YouTube6 INT, Instagram6 INT, LinkedIn6 INT, Google6 INT, Twitter6 INT, WhatsApp6 INT, Messenger6 INT,
                    SnapChat6 INT, Classmates6 INT, Academia6 INT, StudiVZ6 INT, EducaNetwork6 INT, Edmodo6 INT, Schoology6 INT, Brainly6 INT,
                    Eduredes6 INT, Docsity6 INT, OtraEducacion6 INT, RedAlumnos6 INT, Educared6 INT, Eduteka6 INT, Skype6 INT, Badoo6 INT, total6 INT,
                    Facebook7 INT, YouTube7 INT, Instagram7 INT, LinkedIn7 INT, Google7 INT, Twitter7 INT, WhatsApp7 INT, Messenger7 INT,
                    SnapChat7 INT, Classmates7 INT, Academia7 INT, StudiVZ7 INT, EducaNetwork7 INT, Edmodo7 INT, Schoology7 INT, Brainly7 INT,
                    Eduredes7 INT, Docsity7 INT, OtraEducacion7 INT, RedAlumnos7 INT, Educared7 INT, Eduteka7 INT, Skype7 INT, Badoo7 INT, total7 INT,
                    Facebook8 INT, YouTube8 INT, Instagram8 INT, LinkedIn8 INT, Google8 INT, Twitter8 INT, WhatsApp8 INT, Messenger8 INT,
                    SnapChat8 INT, Classmates8 INT, Academia8 INT, StudiVZ8 INT, EducaNetwork8 INT, Edmodo8 INT, Schoology8 INT, Brainly8 INT,
                    Eduredes8 INT, Docsity8 INT, OtraEducacion8 INT, RedAlumnos8 INT, Educared8 INT, Eduteka8 INT, Skype8 INT, Badoo8 INT, total8 INT,
                    Facebook9 INT, YouTube9 INT, Instagram9 INT, LinkedIn9 INT, Google9 INT, Twitter9 INT, WhatsApp9 INT, Messenger9 INT,
                    SnapChat9 INT, Classmates9 INT, Academia9 INT, StudiVZ9 INT, EducaNetwork9 INT, Edmodo9 INT, Schoology9 INT, Brainly9 INT,
                    Eduredes9 INT, Docsity9 INT, OtraEducacion9 INT, RedAlumnos9 INT, Educared9 INT, Eduteka9 INT, Skype9 INT, Badoo9 INT, total9 INT,
                    Facebook10 INT, YouTube10 INT, Instagram10 INT, LinkedIn10 INT, Google10 INT, Twitter10 INT, WhatsApp10 INT, Messenger10 INT,
                    SnapChat10 INT, Classmates10 INT, Academia10 INT, StudiVZ10 INT, EducaNetwork10 INT, Edmodo10 INT, Schoology10 INT, Brainly10 INT,
                    Eduredes10 INT, Docsity10 INT, OtraEducacion10 INT, RedAlumnos10 INT, Educared10 INT, Eduteka10 INT, Skype10 INT, Badoo10 INT, total10 INT,
                    Facebook11 INT, YouTube11 INT, Instagram11 INT, LinkedIn11 INT, Google11 INT, Twitter11 INT, WhatsApp11 INT, Messenger11 INT,
                    SnapChat11 INT, Classmates11 INT, Academia11 INT, StudiVZ11 INT, EducaNetwork11 INT, Edmodo11 INT, Schoology11 INT, Brainly11 INT,
                    Eduredes11 INT, Docsity11 INT, OtraEducacion11 INT, RedAlumnos11 INT, Educared11 INT, Eduteka11 INT, Skype11 INT, Badoo11 INT, total11 INT,
                    Facebook12 INT, YouTube12 INT, Instagram12 INT, LinkedIn12 INT, Google12 INT, Twitter12 INT, WhatsApp12 INT, Messenger12 INT,
                    SnapChat12 INT, Classmates12 INT, Academia12 INT, StudiVZ12 INT, EducaNetwork12 INT, Edmodo12 INT, Schoology12 INT, Brainly12 INT,
                    Eduredes12 INT, Docsity12 INT, OtraEducacion12 INT, RedAlumnos12 INT, Educared12 INT, Eduteka12 INT, Skype12 INT, Badoo12 INT, total12 INT,
                    Facebook13 INT, YouTube13 INT, Instagram13 INT, LinkedIn13 INT, Google13 INT, Twitter13 INT, WhatsApp13 INT, Messenger13 INT,
                    SnapChat13 INT, Classmates13 INT, Academia13 INT, StudiVZ13 INT, EducaNetwork13 INT, Edmodo13 INT, Schoology13 INT, Brainly13 INT,
                    Eduredes13 INT, Docsity13 INT, OtraEducacion13 INT, RedAlumnos13 INT, Educared13 INT, Eduteka13 INT, Skype13 INT, Badoo13 INT, total13 INT,
                    Facebook14 INT, YouTube14 INT, Instagram14 INT, LinkedIn14 INT, Google14 INT, Twitter14 INT, WhatsApp14 INT, Messenger14 INT,
                    SnapChat14 INT, Classmates14 INT, Academia14 INT, StudiVZ14 INT, EducaNetwork14 INT, Edmodo14 INT, Schoology14 INT, Brainly14 INT,
                    Eduredes14 INT, Docsity14 INT, OtraEducacion14 INT, RedAlumnos14 INT, Educared14 INT, Eduteka14 INT, Skype14 INT, Badoo14 INT, total14 INT,
                    Facebook15 INT, YouTube15 INT, Instagram15 INT, LinkedIn15 INT, Google15 INT, Twitter15 INT, WhatsApp15 INT, Messenger15 INT,
                    SnapChat15 INT, Classmates15 INT, Academia15 INT, StudiVZ15 INT, EducaNetwork15 INT, Edmodo15 INT, Schoology15 INT, Brainly15 INT,
                    Eduredes15 INT, Docsity15 INT, OtraEducacion15 INT, RedAlumnos15 INT, Educared15 INT, Eduteka15 INT, Skype15 INT, Badoo15 INT, total15 INT,
                    Facebook16 INT, YouTube16 INT, Instagram16 INT, LinkedIn16 INT, Google16 INT, Twitter16 INT, WhatsApp16 INT, Messenger16 INT,
                    SnapChat16 INT, Classmates16 INT, Academia16 INT, StudiVZ16 INT, EducaNetwork16 INT, Edmodo16 INT, Schoology16 INT, Brainly16 INT,
                    Eduredes16 INT, Docsity16 INT, OtraEducacion16 INT, RedAlumnos16 INT, Educared16 INT, Eduteka16 INT, Skype16 INT, Badoo16 INT, total16 INT,
                    Facebook17 INT, YouTube17 INT, Instagram17 INT, LinkedIn17 INT, Google17 INT, Twitter17 INT, WhatsApp17 INT, Messenger17 INT,
                    SnapChat17 INT, Classmates17 INT, Academia17 INT, StudiVZ17 INT, EducaNetwork17 INT, Edmodo17 INT, Schoology17 INT, Brainly17 INT,
                    Eduredes17 INT, Docsity17 INT, OtraEducacion17 INT, RedAlumnos17 INT, Educared17 INT, Eduteka17 INT, Skype17 INT, Badoo17 INT, total17 INT,
                    otro VARCHAR(20), total18 INT)
