CREATE TABLE cuestionario2 (matricula INT, cuatrimestre INT, edad INT, sexo INT, carrera INT,
            computadora INT, laptop INT, tablet INT, smart INT, noTengo INT,
            Facebook1 INT, Badoo1 INT, Instagram1 INT, GoogleMas1 INT, Twitter1 INT, Schoology1 INT, Eduteka1 INT, Moodle1 INT, Claroline1 INT,
            Edmodo1 INT, WhatsApp1 INT, Spotify1 INT, Messenger1 INT, Softonic1 INT, Pandora1 INT, Web2_01 INT, Wikipedia1 INT, Google1 INT,
            Windows1 INT, YouTube1 INT, MSN1 INT, Yahoo1 INT,
            Facebook2 INT, Badoo2 INT, Instagram2 INT, GoogleMas2 INT, Twitter2 INT, Schoology2 INT, Eduteka2 INT, Moodle2 INT, Claroline2 INT,
            Edmodo2 INT, WhatsApp2 INT, Spotify2 INT, Messenger2 INT, Softonic2 INT, Pandora2 INT, Web2_02 INT, Wikipedia2 INT, Google2 INT,
            Windows2 INT, YouTube2 INT, MSN2 INT, Yahoo2 INT,
            Facebook3 INT, Badoo3 INT, Instagram3 INT, GoogleMas3 INT, Twitter3 INT, Schoology3 INT, Eduteka3 INT, Moodle3 INT, Claroline3 INT,
            Edmodo3 INT, WhatsApp3 INT, Spotify3 INT, Messenger3 INT, Softonic3 INT, Pandora3 INT, Web2_03 INT, Wikipedia3 INT, Google3 INT,
            Windows3 INT, YouTube3 INT, MSN3 INT, Yahoo3 INT,
            Facebook4 INT, Badoo4 INT, Instagram4 INT, GoogleMas4 INT, Twitter4 INT, Schoology4 INT, Eduteka4 INT, Moodle4 INT, Claroline4 INT,
            Edmodo4 INT, WhatsApp4 INT, Spotify4 INT, Messenger4 INT, Softonic4 INT, Pandora4 INT, Web2_04 INT, Wikipedia4 INT, Google4 INT,
            Windows4 INT, YouTube4 INT, MSN4 INT, Yahoo4 INT,
            Facebook5 INT, Badoo5 INT, Instagram5 INT, GoogleMas5 INT, Twitter5 INT, Schoology5 INT, Eduteka5 INT, Moodle5 INT, Claroline5 INT,
            Edmodo5 INT, WhatsApp5 INT, Spotify5 INT, Messenger5 INT, Softonic5 INT, Pandora5 INT, Web2_05 INT, Wikipedia5 INT, Google5 INT,
            Windows5 INT, YouTube5 INT, MSN5 INT, Yahoo5 INT,
            Facebook6 INT, Badoo6 INT, Instagram6 INT, GoogleMas6 INT, Twitter6 INT, Schoology6 INT, Eduteka6 INT, Moodle6 INT, Claroline6 INT,
            Edmodo6 INT, WhatsApp6 INT, Spotify6 INT, Messenger6 INT, Softonic6 INT, Pandora6 INT, Web2_06 INT, Wikipedia6 INT, Google6 INT,
            Windows6 INT, YouTube6 INT, MSN6 INT, Yahoo6 INT,
            Facebook7 INT, Badoo7 INT, Instagram7 INT, GoogleMas7 INT, Twitter7 INT, Schoology7 INT, Eduteka7 INT, Moodle7 INT, Claroline7 INT,
            Edmodo7 INT, WhatsApp7 INT, Spotify7 INT, Messenger7 INT, Softonic7 INT, Pandora7 INT, Web2_07 INT, Wikipedia7 INT, Google7 INT,
            Windows7 INT, YouTube7 INT, MSN7 INT, Yahoo7 INT,
            Facebook8 INT, Badoo8 INT, Instagram8 INT, GoogleMas8 INT, Twitter8 INT, Schoology8 INT, Eduteka8 INT, Moodle8 INT, Claroline8 INT,
            Edmodo8 INT, WhatsApp8 INT, Spotify8 INT, Messenger8 INT, Softonic8 INT, Pandora8 INT, Web2_08 INT, Wikipedia8 INT, Google8 INT,
            Windows8 INT, YouTube8 INT, MSN8 INT, Yahoo8 INT,
            Facebook9 INT, Badoo9 INT, Instagram9 INT, GoogleMas9 INT, Twitter9 INT, Schoology9 INT, Eduteka9 INT, Moodle9 INT, Claroline9 INT,
            Edmodo9 INT, WhatsApp9 INT, Spotify9 INT, Messenger9 INT, Softonic9 INT, Pandora9 INT, Web2_09 INT, Wikipedia9 INT, Google9 INT,
            Windows9 INT, YouTube9 INT, MSN9 INT, Yahoo9 INT,
            Facebook10 INT, Badoo10 INT, Instagram10 INT, GoogleMas10 INT, Twitter10 INT, Schoology10 INT, Eduteka10 INT, Moodle10 INT, Claroline10 INT,
            Edmodo10 INT, WhatsApp10 INT, Spotify10 INT, Messenger10 INT, Softonic10 INT, Pandora10 INT, Web2_010 INT, Wikipedia10 INT, Google10 INT,
            Windows10 INT, YouTube10 INT, MSN10 INT, Yahoo10 INT,
            Facebook11 INT, Badoo11 INT, Instagram11 INT, GoogleMas11 INT, Twitter11 INT, Schoology11 INT, Eduteka11 INT, Moodle11 INT, Claroline11 INT,
            Edmodo11 INT, WhatsApp11 INT, Spotify11 INT, Messenger11 INT, Softonic11 INT, Pandora11 INT, Web2_011 INT, Wikipedia11 INT, Google11 INT,
            Windows11 INT, YouTube11 INT, MSN11 INT, Yahoo11 INT,
            Facebook12 INT, Badoo12 INT, Instagram12 INT, GoogleMas12 INT, Twitter12 INT, Schoology12 INT, Eduteka12 INT, Moodle12 INT, Claroline12 INT,
            Edmodo12 INT, WhatsApp12 INT, Spotify12 INT, Messenger12 INT, Softonic12 INT, Pandora12 INT, Web2_012 INT, Wikipedia12 INT, Google12 INT,
            Windows12 INT, YouTube12 INT, MSN12 INT, Yahoo12 INT,
            Facebook13 INT, Badoo13 INT, Instagram13 INT, GoogleMas13 INT, Twitter13 INT, Schoology13 INT, Eduteka13 INT, Moodle13 INT, Claroline13 INT,
            Edmodo13 INT, WhatsApp13 INT, Spotify13 INT, Messenger13 INT, Softonic13 INT, Pandora13 INT, Web2_013 INT, Wikipedia13 INT, Google13 INT,
            Windows13 INT, YouTube13 INT, MSN13 INT, Yahoo13 INT,
            Facebook14 INT, Badoo14 INT, Instagram14 INT, GoogleMas14 INT, Twitter14 INT, Schoology14 INT, Eduteka14 INT, Moodle14 INT, Claroline14 INT,
            Edmodo14 INT, WhatsApp14 INT, Spotify14 INT, Messenger14 INT, Softonic14 INT, Pandora14 INT, Web2_014 INT, Wikipedia14 INT, Google14 INT,
            Windows14 INT, YouTube14 INT, MSN14 INT, Yahoo14 INT,
            Facebook15 INT, Badoo15 INT, Instagram15 INT, GoogleMas15 INT, Twitter15 INT, Schoology15 INT, Eduteka15 INT, Moodle15 INT, Claroline15 INT,
            Edmodo15 INT, WhatsApp15 INT, Spotify15 INT, Messenger15 INT, Softonic15 INT, Pandora15 INT, Web2_015 INT, Wikipedia15 INT, Google15 INT,
            Windows15 INT, YouTube15 INT, MSN15 INT, Yahoo15 INT,
            otro VARCHAR(250),
            total_redes INT, total_plataformas INT, total_apps INT, total_comunidades INT, total_internet INT);
